'use strict';

/*
 * Lista oficial dos grupos (GRUPO / NÍVEL / MODALIDADE) da SEDUC.
 *
 * É a espinha dorsal da consolidação: os dois documentos são reduzidos a
 * esta lista, e um grupo que não aparecer em nenhum deles ainda assim é
 * mostrado — zerado — para não sumir da conferência.
 */

const GRUPOS_OFICIAIS = [
  "ADMINISTRATIVO / ADMINISTRATIVO / ADMINISTRATIVO",
  "ADMINISTRATIVO / ADMINISTRATIVO / CONSELHO",
  "ADMINISTRATIVO / ADMINISTRATIVO / EDUCAÇÃO ESPECIAL",
  "ADMINISTRATIVO / ADMINISTRATIVO / EDUCAÇÃO DE JOVENS E ADULTOS",
  "ADMINISTRATIVO / ADMINISTRATIVO / GESTÃO",
  "ADMINISTRATIVO / ADMINISTRATIVO / SECRETARIO DE EDUCAÇÃO E ADJUNTOS",
  "ADMINISTRATIVO / ADMINISTRATIVO / PRIVADOS DE LIBERDADE",
  "ADMINISTRATIVO / ADMINISTRATIVO / REGULAR",
  "ADMINISTRATIVO / ATENDIMENTO EDUCACIONAL ESPECIAL / EDUCAÇÃO ESPECIAL",
  "ADMINISTRATIVO / ENSINO FUNDAMENTAL / ADMINISTRATIVO",
  "ADMINISTRATIVO / ENSINO FUNDAMENTAL / EDUCAÇÃO ESPECIAL",
  "ADMINISTRATIVO / ENSINO FUNDAMENTAL / EDUCAÇÃO INDIGENA",
  "ADMINISTRATIVO / ENSINO FUNDAMENTAL / EDUCAÇÃO DE JOVENS E ADULTOS",
  "ADMINISTRATIVO / ENSINO FUNDAMENTAL / GESTÃO",
  "ADMINISTRATIVO / ENSINO FUNDAMENTAL / ENSINO MÉDIO EM TEMPO INTEGRAL",
  "ADMINISTRATIVO / ENSINO FUNDAMENTAL / REGULAR",
  "ADMINISTRATIVO / EDUCAÇÃO INFANTIL / CRECHE",
  "ADMINISTRATIVO / EDUCAÇÃO INFANTIL / REGULAR",
  "ADMINISTRATIVO / ENSINO MÉDIO / ADMINISTRATIVO",
  "ADMINISTRATIVO / ENSINO MÉDIO / EDUCAÇÃO ESPECIAL",
  "ADMINISTRATIVO / ENSINO MÉDIO / EDUCAÇÃO INDIGENA",
  "ADMINISTRATIVO / ENSINO MÉDIO / EDUCAÇÃO DE JOVENS E ADULTOS",
  "ADMINISTRATIVO / ENSINO MÉDIO / EDUCAÇÃO PROFISSIONAL TÉCNICA",
  "ADMINISTRATIVO / ENSINO MÉDIO / GESTÃO",
  "ADMINISTRATIVO / ENSINO MÉDIO / ENSINO MÉDIO EM TEMPO INTEGRAL",
  "ADMINISTRATIVO / ENSINO MÉDIO / PRIVADOS DE LIBERDADE",
  "ADMINISTRATIVO / ENSINO MÉDIO / REGULAR",
  "ADMINISTRATIVO / EDUCAÇÃO PROFISSIONAL NÍVEL TÉCNICO / EDUCAÇÃO PROFISSIONAL TÉCNICA",
  "ADMINISTRATIVO / EDUCAÇÃO PROFISSIONAL NÍVEL TÉCNICO / REGULAR",
  "MAGISTÉRIO / ADMINISTRATIVO / ADMINISTRATIVO",
  "MAGISTÉRIO / ADMINISTRATIVO / CONSELHO",
  "MAGISTÉRIO / ADMINISTRATIVO / EDUCAÇÃO ESPECIAL",
  "MAGISTÉRIO / ADMINISTRATIVO / EDUCAÇÃO DE JOVENS E ADULTOS",
  "MAGISTÉRIO / ADMINISTRATIVO / EDUCAÇÃO PROFISSIONAL TÉCNICA",
  "MAGISTÉRIO / ADMINISTRATIVO / GESTÃO",
  "MAGISTÉRIO / ADMINISTRATIVO / ENSINO MÉDIO EM TEMPO INTEGRAL",
  "MAGISTÉRIO / ADMINISTRATIVO / PRIVADOS DE LIBERDADE",
  "MAGISTÉRIO / ADMINISTRATIVO / REGULAR",
  "MAGISTÉRIO / ATENDIMENTO EDUCACIONAL ESPECIAL / EDUCAÇÃO ESPECIAL",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / ADMINISTRATIVO",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / EDUCAÇÃO DO CAMPO",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / EDUCAÇÃO ESPECIAL",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / EDUCAÇÃO INDÍGENA",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / EDUCAÇÃO DE JOVENS E ADULTOS",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / EDUCAÇÃO QUILOMBOLA",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / EDUCAÇÃO PROFISSIONAL TÉCNICA",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / GESTÃO",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / ENSINO MÉDIO EM TEMPO INTEGRAL",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / PRIVADOS DE LIBERDADE",
  "MAGISTÉRIO / ENSINO FUNDAMENTAL / REGULAR",
  "MAGISTÉRIO / EDUCAÇÃO INFANTIL / EDUCAÇÃO INDIGENA",
  "MAGISTÉRIO / EDUCAÇÃO INFANTIL / REGULAR",
  "MAGISTÉRIO / ENSINO MÉDIO / ADMINISTRATIVO",
  "MAGISTÉRIO / ENSINO MÉDIO / EDUCAÇÃO DO CAMPO",
  "MAGISTÉRIO / ENSINO MÉDIO / EDUCAÇÃO ESPECIAL",
  "MAGISTÉRIO / ENSINO MÉDIO / EDUCAÇÃO INDÍGENA",
  "MAGISTÉRIO / ENSINO MÉDIO / EDUCAÇÃO DE JOVENS E ADULTOS",
  "MAGISTÉRIO / ENSINO MÉDIO / EDUCAÇÃO QUILOMBOLA",
  "MAGISTÉRIO / ENSINO MÉDIO / EDUCAÇÃO PROFISSIONAL TÉCNICA",
  "MAGISTÉRIO / ENSINO MÉDIO / GESTÃO",
  "MAGISTÉRIO / ENSINO MÉDIO / ENSINO MÉDIO EM TEMPO INTEGRAL",
  "MAGISTÉRIO / ENSINO MÉDIO / PRIVADOS DE LIBERDADE",
  "MAGISTÉRIO / ENSINO MÉDIO / REGULAR",
  "MAGISTÉRIO / EDUCAÇÃO PROFISSIONAL NÍVEL TÉCNICO / ADMINISTRATIVO",
  "MAGISTÉRIO / EDUCAÇÃO PROFISSIONAL NÍVEL TÉCNICO / EDUCAÇÃO ESPECIAL",
  "MAGISTÉRIO / EDUCAÇÃO PROFISSIONAL NÍVEL TÉCNICO / EDUCAÇÃO PROFISSIONAL TÉCNICA",
  "MAGISTÉRIO / EDUCAÇÃO PROFISSIONAL NÍVEL TÉCNICO / REGULAR",
];

/** Sem acento, em caixa alta, só letras e números separados por espaço. */
function normalizar(texto) {
  return String(texto || '')
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .toUpperCase().replace(/[^A-Z0-9]+/g, ' ').trim();
}

/*
 * O relatório da folha corta cada nível do nome num tamanho fixo, e o corte
 * cai no meio da palavra: "EDUCAÇÃO PROFISSIONAL TÉCNICA" vira "EDUC PROFIS
 * TECNIC", às vezes comendo a última palavra inteira. Por isso a comparação
 * é palavra a palavra, cada uma do texto cortado sendo o início da oficial.
 */
function casaComOficial(oficialNormalizado, textoNormalizado) {
  if (oficialNormalizado === textoNormalizado) return true;
  const oficial = oficialNormalizado.split(' ');
  const cortado = textoNormalizado.split(' ');
  if (cortado.length > oficial.length) return false;
  return cortado.every((palavra, i) => oficial[i].startsWith(palavra));
}

const CATALOGO = GRUPOS_OFICIAIS.map((nome) => ({ nome, chave: normalizar(nome) }));

/** Devolve o grupo oficial correspondente ao texto, ou null. */
function acharGrupo(texto) {
  const alvo = normalizar(texto);
  if (!alvo) return null;
  return CATALOGO.find((g) => casaComOficial(g.chave, alvo))
      || CATALOGO.find((g) => casaComOficial(alvo, g.chave))
      || null;
}

module.exports = { GRUPOS_OFICIAIS, CATALOGO, normalizar, casaComOficial, acharGrupo };
